src/explorepy/packet.py
src/explorepy/parser.py
src/explorepy/tools.py

Uses timestamp packages as marker packages and saves them into a separate csv file.

Marker Feature

---

CHANGELOG.rst
src/explorepy/dashboard/dashboard.py

Performance improvement in the dashboard visualization

Bugfix improved visualization performance

---

MANIFEST.in
lib/mac/BTSerialPortBinding.mm
setup.py
src/explorepy/btcpp.py

Added working solution for two different Broadcom chipsets 4364B0 and 4350

Mac bug fix

---

lib/mac/BTSerialPortBinding.h
lib/mac/BTSerialPortBinding.mm
lib/mac/create_shared_lib.sh
lib/mac/swig_interface_wrap.cxx

The new -thread option has been reverted for Mac OS for better functionality.

Bugfix thread

---

src/explorepy/dashboard/dashboard.py
src/explorepy/dashboard/templates/index.html

Autoscaling of GUI on screens with different resolutions

Autoscaling

---

src/explorepy/dashboard/dashboard.py

Disable unnecessary widgets in impedance mode

Disable unnecessary widgets

---

installer/windows/installer.cfg
licenses/LICENSE_sentry_sdk.txt

added new required package for bokeh 2.2.3

---

src/explorepy/btcpp.py

Bugfix sdk

---

setup.py
src/explorepy/cli.py

Update sentry to ignore user input errors in CLI

Bugfix sentry

---

setup.py

update pyedflib dependency version

---

src/explorepy/stream_processor.py

Added remove filters function in stream processor

Feature remove filters

---

lib/linux/ExploreException.h
lib/linux/exploresdk.py
lib/linux/swig_interface.i
lib/linux/swig_interface_wrap.cxx
lib/mac/ExploreException.h
lib/mac/swig_interface.i

This PR is required for linting branch in order to test if API is working properly after linting.

bugfix - No bt patch linux

---

src/explorepy/command.py
src/explorepy/explore.py
src/explorepy/tools.py

Changes:
- Channel count starts with 1 instead of 0
- Only generate Meta file when converting/recording to csv
- Remove timestamp column

Bugfix metadata

---

src/explorepy/command.py
src/explorepy/explore.py
src/explorepy/stream_processor.py

**Bug**: `RuntimeError: Set changed size during iteration`
**Bug description:**
If subscribers' set is changed during the dispatch iteration, this `RuntimeError` is raised.
**How to test if this is fixed?**
Run this code snippet with this branch and also with an old branch:
```
from explorepy.explore import Explore
explore = Explore()
explore.connect(device_name='Explore_CA4C')  # write your device name
explore.record_data('test', do_overwrite=True, duration=100, file_type='csv')
explore.push2lsl(duration=10, block=False)
while True:
explore.stop_lsl()
explore.push2lsl(duration=10, block=False)
```
You should get the runtime error after running the code but it shouldn't happen in the current branch.

Bugfix subscriber set iter

---

src/explorepy/command.py
src/explorepy/explore.py
src/explorepy/stream_processor.py

This PR applies some changes in the device configuration functions to return the status of the config commands.
The changes should be tested along with the Explore Desktop's refactoring branch as the config status is needed there.

Change conf status

---

src/explorepy/stream_processor.py
src/explorepy/tools.py

Please read the related story in Jira.

Edf time correction

---

src/explorepy/tools.py

Fix issue with edf annotations

fix edf recording

---

src/explorepy/btcpp.py
src/explorepy/packet.py
src/explorepy/settings_manager.py
src/explorepy/stream_processor.py
src/explorepy/tools.py

Added new device info with ID-97 and EEG32 class ID- 148

Add parser for new device info and 32 channel packets

---

src/explorepy/parser.py
src/explorepy/serial_client.py
src/explorepy/stream_processor.py

Test script:
```
import explorepy
explorepy.set_bt_interface('usb')
for i in range(10):
exp_device = explorepy.Explore()
exp_device.connect('Explore_DAAV')
exp_device.set_sampling_rate(sampling_rate=4000)
exp_device.record_data( 'file_name' + str(i), do_overwrite=True, duration=10, file_type='csv', block=True)
exp_device.disconnect()
```

Check device name before usb connection

---

.github/workflows/testing.yml

- Updated workflow for macos-latest to install miniconda manually
- Updated upload action from v3 to v4

APIS-1036 Fix Actions workflows

---

src/explorepy/explore.py
src/explorepy/stream_processor.py

- Move impedance mode check to explore.py
- Update command thread variable

Bugfix command thread

---

src/explorepy/packet.py

Also updates IMU with new sensitivities

Updated ORN packet to include parsing for quat

---

examples/eeg2lamp.py
examples/eeg2lamp/EEG_LAMP_ARDUINO/EEG_LAMP_ARDUINO.ino
examples/eeg2lamp/eeg2lamp.py

This PR contains an example script in Python that connects to an Arduino on a given port and sends it 1s or 0s based on the power change in the alpha band (EEG). It also contains the .ino sketch for the Arduino that is required to run the example.
The Arduino controls an LED strip (brightness and colour) based on the input from the port.
This PR additionally contains a very short example for how to feed recorded .bdf files to a client instead of live data from a device (for testing purposes).

Apis 1335 eeg2lamp

---

README.rst
docs/installation.rst
docs/usage.rst

Removed quick installation section, mention linux version of Explore desktop.
Fixed logo display

Update RTD documentation

---

docs/usage.rst
src/explorepy/stream_processor.py

- remove mapped orn topic
- find-device removed from docs
- physical orn calculation also removed

Remove deprecated methods
